> #### **ISSD - Desarrollo de Sistemas de Inteligencia Artificial**  
> Profesor: Sachi, Julio Mariano  
> Alumno: Garcia Alves, Andrés


> GitHub: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; https://github.com/andres-garcia-alves/issd-dsia/tree/main/Proyecto-Final  
> Notebook: &nbsp; https://colab.research.google.com/drive/1pd5cmNriSxK3FQSHNF0YwUbl6c4cecE0?usp=sharing  
> Deploy: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; https://issd-dsia-andres-garcia-alves.streamlit.app/


## ⭐ Proyecto: Agente de Búsqueda Inteligente en Tableros con Costos

## 💡 Parte 1 - Introducción

### 💬 1.1. Descripción resumida

Busco implementar un mini sistema de GPS. 🧭

Para ello, un agente inteligente buscará en un tablero generado de forma aleatoria la ruta óptima.

El sistema se compone de 2 bloques principales:
- Distintos algoritmos de búsqueda (informada y no-informada)
- Una red neuronal que elige el algoritmo de búsqueda más eficiente para un tablero dado.

Conecto de esta manera los 2 temas principales de la materia, a saber: algoritmos de búsqueda y machine learning.

### 🧩 1.2. Descripción general

Un agente debe desplazarse desde una celda inicial hasta una celda objetivo en el tablero (una grilla) que se genera aleatoriamente, y de dimensiones variables (ej. 4×4, 5x5, 6×6, 8×8, etc).

Cada celda tiene un costo distinto de movimiento (1, 2 o 3). Un costo de 1 viene a ser el costo 'normal' de movimiento, luego los costos mayores a 1 simulan ya sean caminos rurales o embotellamientos de tránsito.
El agente debe encontrar la ruta de menor costo total.

Se implementaran distintos algoritmos de búsqueda (BFS, UCS, A*, Greedy), y luego una red neuronal aprenderá a predecir cuál de ellos es el más eficiente (por tiempo y/o costo total) según las características del tablero recibido.

### ⚙️ 1.3. Descripción técnica

Se dispone de un entorno tipo grilla/laberinto (por ejemplo 4x4, 6x6, etc) donde un agente busca la salida minimizando el costo total de movimiento, con casillas que pueden tener distintos pesos (costos).

Se implementan distintos algoritmos de búsqueda informada/no-informada:
- BFS (búsqueda a lo ancho)
- UCS (Uniform Cost Search)
- Greedy Best-First Search
- A* (con heurística de distancia Manhattan)

Luego, se agrega una red neuronal (en TensorFlow/Keras) para predecir cuál algoritmo de búsqueda conviene aplicar, dadas ciertas características del tablero (dimensión, cantidad y distribución de obstáculos, sus costos, etc).

Para entrenar la red neuronal se generá un dataset sintético con tableros de múltiples tamaños y disposiciones aleatorias.  
Para ello, se reutilizan los algoritmos de búsqueda disponibles en el sistema, bajo el siguiente esquema:
- Generar un tablero de tamaño y disposición aleatoria
- Pasar el tablero generado por cada uno de los algoritmos de búsqueda disponibles
- Evaluar y guardar métricas de desempeño de cada algoritmo en el tablero actual
- Repetir N veces los pasos previos en distintos tableros, hasta generar suficientes datos de entrenamiento.

La red neuronal estará resolviendo un problema de clasificación: de los datos guardados, las columnas con las métricas serán los features para el entrenamiento, y la columna que identifica al algoritmo que generó esas métricas el target.

### 🏗️ 1.4. Estructura general del Proyecto

📘 Proyecto_Final.ipynb  
│  
├── 1. Generación de tableros sintéticos  
├── 2. Implementación de algoritmos de búsqueda  
├── 3. Creación del dataset (features + etiqueta)  
├── 4. Análisis exploratorio (EDA)  
├── 5. Preprocesamiento de datos  
├── 6. Red Neuronal (TensorFlow/Keras)  
├── 7. Evaluación y métricas  
└── 8. Conclusiones  
&nbsp;

### 🔍 1.5. Implementación de los algoritmos de búsqueda

Se implementan versiones simples de:
* BFS (Breadth-First Search) → ignora pesos (ideal para comparar).
* Uniform Cost Search (Dijkstra)
* Greedy Best-First Search → con heurística de distancia Manhattan.
* A* → heurística + costo acumulado.

Cada algoritmo retorna las siguiente métricas:
* costo_total
* nodos_expandidos
* tiempo_ejecucion

Con estas métricas se evalúan y comparan luego sus rendimientos.

### 🧮 1.6. Creación del dataset

Por cada tablero:
* Probarlo en los 4 algoritmos.
* Calcular y guardar en una fila:
  - tamaño
  - costo_promedio
  - varianza_costos
  - densidad_costo_alto
  - mejor_algoritmo

### 📈 1.7. Análisis Exploratorio (EDA)

Se utiliza Matplotlib y Seaborn para visualizar:
* Distribución de tamaños de tablero.
* Relación entre costo promedio y algoritmo óptimo.
* Frecuencia de cada algoritmo como "óptimo".

### 🪚 1.8. Preprocesamiento de datos

* Chequeo de duplicados
* Chequeo de nulos
* Convertir etiquetas (nombre del algoritmo) a numéricas (LabelEncoder).
* Normalizar variables numéricas (StandardScaler)

### 🧠 1.9. Red neuronal en TensorFlow/Keras

* Un modelo simple de clasificación multiclase, una por cada algoritmo de búsqueda.


### 📝 1.10. Evaluación y métricas

Se incluirán:
* Exactitud (accuracy)
* Matriz de confusión
* Reporte de clasificación

### 🛠️ 1.11. Bibliotecas utilizadas

| Propósito                          | Librería(s)                    |
| ---------------------------------- | ------------------------------ |
| Generación y manipulación de datos | `numpy`, `pandas`              |
| Visualización                      | `matplotlib`, `seaborn`, `PIL` |
| Implementación de búsquedas        | `heapq` (para UCS y A*)        |
| Red neuronal                       | `tensorflow.keras`, `pickle`   |
| Preprocesamiento                   | `sklearn`                      |
| Miscelaneas                        | `time`, `random`, `tqdm`, `urllib` |

<br/>

### 🧾 1.12. Estructura del Informe Final

| Sección                 | Contenido resumido |
| ----------------------- | -------------------|
| **Introducción**        | Explicación del problema del agente en el tablero. |
|                         | Justificación del interés (búsqueda inteligente, optimización de recursos). |
| **Metodología**         | Bibliotecas usadas (`numpy`, `pandas`, `matplotlib`, `tensorflow`, `sklearn`) |
|                         | Descripción del proceso de generación de tableros y entrenamiento. |
| **Resultados**          | Tablas y gráficos de rendimiento del modelo. |
|                         | Ejemplos de tableros y caminos. |
| **Análisis conceptual** | Relación entre búsqueda heurística y optimización del modelo neuronal. |
| **Conclusión**          | Observaciones y posibles mejoras (ej. tableros más grandes, más algoritmos, etc). |

<br/>
<br/>

## 📊 Parte 2 - Dataset Sintético y Algoritmos de Búsqueda

### 📚 2.1. Bibliotecas necesarias

In [1]:
!pip install numpy pandas matplotlib seaborn

### 🧩 2.2. Importaciones y configuración inicial

In [2]:
import numpy as np
import pandas as pd
import time
import random
import heapq
from collections import deque
from tqdm import tqdm  # barra de progreso

### 🧱 2.3. Generación de tableros sintéticos

Cada tablero tiene:
- Tamaño variable (4x4 hasta 8x8).
- Celdas con costos 1, 2 o 3.
- Inicio (posición: 0,0), Meta (posición: n-1,n-1).


In [3]:
# Generar un tablero de NxN con costos 1, 2 o 3
def generar_tablero(n=6):
  tablero = np.random.choice([1, 2, 3], size=(n, n), p=[0.6, 0.3, 0.1])
  tablero[0,0] = 0    # costo en la celda de inicio
  tablero[-1,-1] = 1  # costo en la celda final
  return tablero

In [4]:
tablero = generar_tablero(6)
print(tablero)

[[0 1 1 1 1 3]
 [2 1 1 1 1 1]
 [1 1 2 3 2 1]
 [2 3 1 2 1 3]
 [1 1 1 2 1 3]
 [1 3 2 2 3 1]]


### 🚶 2.4. Movimiento y Heurística

In [5]:
# Devuelve los vecinos válidos (arriba, abajo, izquierda, derecha)
def vecinos(pos, n):
    x, y = pos
    movs = [(x+1, y), (x-1, y), (x, y+1), (x, y-1)]
    return [(nx, ny) for nx, ny in movs if 0 <= nx < n and 0 <= ny < n]

In [6]:
# Se utiliza la distancia Manhattan para la Heurística
def heuristica(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

### 🔍 2.5. Algoritmo BFS (búsqueda en anchura)

In [7]:
# BFS (versión simple que no considera pesos)
def busqueda_bfs(tablero):
    timespan = time.time()
    n = tablero.shape[0]
    start, goal = (0, 0), (n-1, n-1)
    cola = [(start, [start])]
    visitados = set()
    nodos_exp = 0

    while cola:
        actual, camino = cola.pop(0)
        if actual in visitados: continue
        visitados.add(actual)
        nodos_exp += 1

        if actual == goal:
            costo_total = sum(tablero[x, y] for x, y in camino)
            timespan = time.time() - timespan
            return costo_total, nodos_exp, timespan, camino

        for nx, ny in vecinos(actual, n):
            if (nx, ny) not in visitados:
                cola.append(((nx, ny), camino + [(nx, ny)]))

    timespan = time.time() - timespan
    return np.inf, nodos_exp, timespan, []

### 🔍 2.6. Algoritmo A* (A estrella)

In [8]:
# Búsqueda A estrella
def busqueda_a_star(tablero):
    timespan = time.time()
    n = tablero.shape[0]
    start, goal = (0, 0), (n - 1, n - 1)
    open_set = [(heuristica(start, goal), 0, start, [start])]
    visitados = set()
    nodos_exp = 0

    while open_set:
        _, costo_actual, actual, camino = heapq.heappop(open_set)

        if actual in visitados: continue
        visitados.add(actual)
        nodos_exp += 1

        if actual == goal:
            timespan = time.time() - timespan
            return costo_actual + tablero[goal], nodos_exp, timespan, camino + [goal]

        for nx, ny in vecinos(actual, n):
            if (nx, ny) not in visitados:
                nuevo_costo = costo_actual + tablero[nx, ny]
                f = nuevo_costo + heuristica((nx, ny), goal)
                heapq.heappush(open_set, (f, nuevo_costo, (nx, ny), camino + [(nx, ny)]))

    timespan = time.time() - timespan
    return np.inf, nodos_exp, timespan, []

### 🔍 2.7. Algoritmos A*, UCS y Greedy

In [9]:
# Búsqueda genérica con cola de prioridad (UCS / Greedy / A*)
def busqueda_generica(tablero, algoritmo="A*"):
    timespan = time.time()
    n = len(tablero)
    start, goal = (0,0), (n-1,n-1)
    movimientos = [(0,1),(1,0),(-1,0),(0,-1)]

    open_list = []
    heapq.heappush(open_list, (0, start, [start]))
    cost_so_far = {start: 0}
    nodos_exp = 0

    while open_list:
        prioridad, actual, camino = heapq.heappop(open_list)
        nodos_exp += 1

        # si se llegó a la meta, devolver el costo, nodos, tiempo y el camino completo
        if actual == goal:
            timespan = time.time() - timespan
            return cost_so_far.get(goal, np.inf), nodos_exp, timespan, camino

        for dx, dy in movimientos:
            nx, ny = actual[0] + dx, actual[1] + dy
            if 0 <= nx < n and 0 <= ny < n:
                nuevo = (nx, ny)
                nuevo_costo = cost_so_far[actual] + tablero[nx, ny]

                # actualizar si se encontró un mejor costo
                if nuevo not in cost_so_far or nuevo_costo < cost_so_far[nuevo]:
                    cost_so_far[nuevo] = nuevo_costo

                    # calcular prioridad según el algoritmo
                    if algoritmo == "UCS":
                        prioridad_nuevo = nuevo_costo
                    elif algoritmo == "Greedy":
                        prioridad_nuevo = heuristica(nuevo, goal)
                    elif algoritmo == "A*":
                        prioridad_nuevo = nuevo_costo + heuristica(nuevo, goal)
                    else:
                        raise ValueError(f"Estrategia desconocida: {algoritmo}")

                    # insertar en la heap con el camino actualizado (incluye start)
                    heapq.heappush(open_list, (prioridad_nuevo, nuevo, camino + [nuevo]))

    timespan = time.time() - timespan
    return np.inf, nodos_exp, timespan, []

### ⏱️ 2.8. Pruebas iniciales

In [10]:
tablero = generar_tablero(6)
print("Tablero:")
print(tablero)
print()

for alg, func in {"BFS": busqueda_bfs, "A*": busqueda_a_star}.items():
    costo, nodos, tiempo, camino = func(tablero)
    print(f"{alg.ljust(4)}: costo={costo}, nodos={nodos}, tiempo={tiempo:.6f}s, camino={camino}")

Tablero:
[[0 1 1 1 1 1]
 [1 1 1 3 1 2]
 [1 2 1 3 2 1]
 [2 1 2 2 2 1]
 [1 1 1 1 2 1]
 [1 1 1 1 3 1]]

BFS : costo=13, nodos=36, tiempo=0.000115s, camino=[(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5)]
A*  : costo=12, nodos=30, tiempo=0.000120s, camino=[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 5), (2, 5), (3, 5), (4, 5), (5, 5), (5, 5)]


In [11]:
tablero = generar_tablero(6)
print("Tablero:")
print(tablero)
print()

results_a_star = busqueda_generica(tablero, algoritmo="A*")
results_ucs = busqueda_generica(tablero, algoritmo="UCS")
results_greedy = busqueda_generica(tablero, algoritmo="Greedy")

print(f"A*     : costo={results_a_star[0]}, nodos={results_a_star[1]}, tiempo={results_a_star[2]:.6f}s, camino={results_a_star[3]}")
print(f"UCS*   : costo={results_ucs[0]}, nodos={results_ucs[1]}, tiempo={results_ucs[2]:.6f}s, camino={results_ucs[3]}")
print(f"Greedy : costo={results_greedy[0]}, nodos={results_greedy[1]}, tiempo={results_greedy[2]:.6f}s, camino={results_greedy[3]}")

Tablero:
[[0 3 1 1 1 2]
 [1 1 1 1 1 2]
 [3 2 1 1 1 1]
 [1 1 1 3 2 1]
 [3 2 1 1 1 1]
 [1 1 3 2 1 1]]

A*     : costo=10, nodos=18, tiempo=0.000088s, camino=[(0, 0), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (2, 4), (2, 5), (3, 5), (4, 5), (5, 5)]
UCS*   : costo=10, nodos=36, tiempo=0.000096s, camino=[(0, 0), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (2, 4), (2, 5), (3, 5), (4, 5), (5, 5)]
Greedy : costo=14, nodos=11, tiempo=0.000033s, camino=[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 5), (2, 5), (3, 5), (4, 5), (5, 5)]


### 🛠️ 2.9. Funciones Auxiliares

In [12]:
def probar_algoritmos(tablero):
    resultados = {
        "BFS": busqueda_bfs(tablero),
        "A*": busqueda_generica(tablero, algoritmo="A*"),
        "UCS": busqueda_generica(tablero, algoritmo="UCS"),
        "Greedy": busqueda_generica(tablero, algoritmo="Greedy")
    }

    # Crear una lista de tuplas con los 3 criterios a medir
    metricas = {
        alg: (res[0], res[1], res[2])  # costo, nodos_expandidos, tiempo
        for alg, res in resultados.items()
    }

    # Seleccionar el mejor algoritmo
    # Criterio: primero 'costo', en caso de empate 'nodos expandidos', y en última instancia 'tiempo de computo'
    mejor_alg = min(metricas, key=lambda k: metricas[k])

    return mejor_alg, resultados

### 🧱 2.10. Generador del dataset sintético

In [13]:
# Genera un dataset con 'n_samples' tableros aleatorios y los resultados
# de distintos algoritmos de búsqueda aplicados sobre cada uno de ellos.
def generar_dataset(n_samples=500, tamanios=(4,5,6,7,8)):
    registros = []

    for _ in tqdm(range(n_samples), desc=f"Generando tableros"):
        n = random.choice(tamanios)
        tablero = generar_tablero(n)

        # características del tablero
        costo_prom = np.mean(tablero)           # promedio
        var_costo = np.var(tablero)             # varianza
        densidad_cost3 = np.mean(tablero == 3)  # prom de celdas con costo = 3

        # evaluar el tablero x separado en todos los algoritmos
        mejor_alg, resultados = probar_algoritmos(tablero)

        registros.append({
            "tamanio": n,
            "costo_prom": costo_prom,
            "var_costo": var_costo,
            "densidad_cost3": densidad_cost3,
            "costo_BFS": resultados["BFS"],
            "costo_A*": resultados["A*"],
            "costo_UCS": resultados["UCS"],
            "costo_Greedy": resultados["Greedy"],
            "mejor_alg": mejor_alg
        })

    df = pd.DataFrame(registros)
    return df

### 🚀 2.11. Generar el dataset

In [14]:
df = generar_dataset(n_samples=1000, tamanios=(3,4,5,6,7,8,9,10))

Generando tableros: 100%|██████████| 1000/1000 [00:00<00:00, 1175.56it/s]


In [15]:
df.sample(5)

tamanio  costo_prom  var_costo  densidad_cost3  \
573        9    1.456790   0.519738        0.123457   
599        7    1.653061   0.634736        0.183673   
481        5    1.320000   0.297600        0.000000   
176        3    1.111111   0.543210        0.111111   
217        5    1.240000   0.262400        0.000000   

                                             costo_BFS  \
573  (21, 81, 0.0002644062042236328, [(0, 0), (1, 0...   
599  (22, 49, 0.0001742839813232422, [(0, 0), (1, 0...   
481  (9, 25, 8.20159912109375e-05, [(0, 0), (1, 0),...   
176  (6, 9, 2.5987625122070312e-05, [(0, 0), (1, 0)...   
217  (10, 25, 5.650520324707031e-05, [(0, 0), (1, 0...   

                                              costo_A*  \
573  (16, 32, 0.0002110004425048828, [(0, 0), (0, 1...   
599  (14, 37, 0.00020313262939453125, [(0, 0), (0, ...   
481  (9, 16, 0.0012285709381103516, [(0, 0), (1, 0)...   
176  (4, 8, 2.4557113647460938e-05, [(0, 0), (0, 1)...   
217  (8, 10, 3.886222839355469e-05, [(0, 0), (0, 1)...   

                                             costo_UCS  \
573  (16, 80, 0.0004048347473144531, [(0, 0), (0, 1...   
599  (14, 48, 0.00021266937255859375, [(0, 0), (0, ...   
481  (9, 25, 0.0001347064971923828, [(0, 0), (1, 0)...   
176  (4, 8, 1.621246337890625e-05, [(0, 0), (0, 1),...   
217  (8, 25, 5.91278076171875e-05, [(0, 0), (0, 1),...   

                                          costo_Greedy mejor_alg  
573  (24, 17, 9.107589721679688e-05, [(0, 0), (0, 1...        A*  
599  (15, 13, 0.00011396408081054688, [(0, 0), (0, ...        A*  
481  (12, 9, 4.220008850097656e-05, [(0, 0), (0, 1)...        A*  
176  (4, 5, 1.0728836059570312e-05, [(0, 0), (0, 1)...    Greedy  
217  (10, 9, 3.0040740966796875e-05, [(0, 0), (0, 1...        A*

### 💾 2.12. Guardar el dataset

Para una revisión exaustiva y posibilidad de re-uso posterior.

In [16]:
df.to_csv("dataset_busquedas.csv", index=False)
print("Dataset guardado en 'dataset_busquedas.csv'")

Dataset guardado en 'dataset_busquedas.csv'


## Parte 3 - EDA y Preprocesamiento

### 🧩 3.1. Importaciones y configuración inicial

In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### 👀 3.2. Estadísticos del dataset

In [25]:
print(df["mejor_alg"].value_counts())
print()

df.describe()

mejor_alg
A*        848
Greedy    117
UCS        35
Name: count, dtype: int64



tamanio   costo_prom    var_costo  densidad_cost3
count  1000.000000  1000.000000  1000.000000     1000.000000
mean      6.585000     1.430439     0.489670        0.093231
std       2.347826     0.129658     0.135169        0.055214
min       3.000000     0.888889     0.098765        0.000000
25%       4.000000     1.367347     0.408341        0.061728
50%       7.000000     1.444444     0.471451        0.093750
75%       9.000000     1.518519     0.556946        0.122449
max      10.000000     1.812500     1.135802        0.333333

### 🪚 3.3. Validación por nulos y duplicados

In [21]:
df.sample(5)

tamanio  costo_prom  var_costo  densidad_cost3  \
29        10    1.570000   0.485100        0.110000   
573        9    1.456790   0.519738        0.123457   
845        4    1.437500   0.621094        0.125000   
80         4    1.375000   0.484375        0.062500   
874        7    1.469388   0.493961        0.102041   

                                             costo_BFS  \
29   (29, 100, 0.00020647048950195312, [(0, 0), (1,...   
573  (21, 81, 0.0002644062042236328, [(0, 0), (1, 0...   
845  (9, 16, 4.6253204345703125e-05, [(0, 0), (1, 0...   
80   (7, 16, 4.0531158447265625e-05, [(0, 0), (1, 0...   
874  (18, 49, 0.00010085105895996094, [(0, 0), (1, ...   

                                              costo_A*  \
29   (20, 44, 0.00015401840209960938, [(0, 0), (0, ...   
573  (16, 32, 0.0002110004425048828, [(0, 0), (0, 1...   
845  (6, 10, 3.123283386230469e-05, [(0, 0), (0, 1)...   
80   (7, 14, 3.8623809814453125e-05, [(0, 0), (1, 0...   
874  (14, 37, 0.00014281272888183594, [(0, 0), (0, ...   

                                             costo_UCS  \
29   (20, 97, 0.00028204917907714844, [(0, 0), (0, ...   
573  (16, 80, 0.0004048347473144531, [(0, 0), (0, 1...   
845  (6, 15, 3.361701965332031e-05, [(0, 0), (0, 1)...   
80   (7, 16, 3.457069396972656e-05, [(0, 0), (1, 0)...   
874  (14, 49, 0.00012159347534179688, [(0, 0), (0, ...   

                                          costo_Greedy mejor_alg  
29   (25, 19, 6.413459777832031e-05, [(0, 0), (0, 1...        A*  
573  (24, 17, 9.107589721679688e-05, [(0, 0), (0, 1...        A*  
845  (6, 7, 1.6689300537109375e-05, [(0, 0), (0, 1)...    Greedy  
80   (8, 7, 2.5033950805664062e-05, [(0, 0), (0, 1)...        A*  
874  (21, 13, 3.457069396972656e-05, [(0, 0), (0, 1...        A*

In [26]:
# eliminar tableros duplicados
print("Tamaño con duplicados:", df.shape)
df.drop_duplicates(inplace=True)
print("Tamaño sin duplicados:", df.shape)

Tamaño con duplicados: (1000, 9)


TypeError: unhashable type: 'list'

In [ ]:
# eliminar tableros con algún dato nulo
# (no debería darse el caso, pero por lo agrego por las dudas)
print("Tamaño con nulos:", df.shape)
df.dropna(inplace=True)
print("Tamaño sin nulos:", df.shape)

### 📈 3.4. Visualización de distribuciones

In [ ]:
sns.countplot(data=df, x="mejor_alg", palette="viridis", hue="mejor_alg")
plt.title("Frecuencia del algoritmo más eficiente")
plt.show()

### 📈 3.5. Correlaciones

In [ ]:
# TODO: CONTINUAR ACA !!!

df_numerico = df.copy()
df_numerico["mejor_alg"] = df_numerico["mejor_alg"].astype("category").cat.codes

# Calcular la matriz de correlación
corr = df_numerico.corr(numeric_only=True)

# Crear el mapa de calor
plt.figure(figsize=(8,6))
sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    center=0,
    fmt=".2f",
    linewidths=0.5,
    square=True
)
plt.title("Mapa de calor de correlaciones entre variables del dataset", fontsize=14)
plt.show()

## 🧠 Parte 4 - Modelo con Red Neuronal (TensorFlow/Keras)

### 📚 4.1. Bibliotecas necesarias

In [ ]:
!pip install tensorflow scikit-learn

### 🧩 4.2. Importaciones y configuración inicial

In [ ]:
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

import tensorflow as tf
from tensorflow.keras import layers, models

import pickle

### 📦 4.3 Cargar el dataset

Al cargar un dataset fijo, en lugar de simplemente tomar la variable **df** de memoria, garantizo la previsibilidad de los datos al momento del entrenamiento.

In [ ]:
ds_path = "https://github.com/andres-garcia-alves/issd-dsia/raw/refs/heads/main/Proyecto-Final/miscelaneos/dataset_busquedas.csv"
# ds_path = "dataset_busquedas.csv"

df = pd.read_csv(ds_path)

In [ ]:
df.sample(5)

### 🔹 4.4. Codificación y Normalización

In [ ]:
# Codificar la variable objetivo
le = LabelEncoder()
df['mejor_alg_enc'] = le.fit_transform(df['mejor_alg'])

# Features y etiquetas
x = df[['tamanio', 'costo_prom', 'var_costo', 'densidad_cost3']]
y = df['mejor_alg_enc']

# Escalar las features
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

# Separación de los datos en train/test
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=1234) # stratify=y,

print("x_train shape:", x_train.shape)
print("Clases codificadas:", dict(zip(le.classes_, le.transform(le.classes_))))

### 🧱 4.5. Definición de la Red Neuronal

In [ ]:
n_clases = len(le.classes_)

model = models.Sequential([
    layers.Input(shape=(x_train.shape[1],)),
    layers.Dense(16, activation='relu'),
    layers.Dense(8, activation='relu'),
    layers.Dense(n_clases, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

### 🚀 4.6. Entrenamiento del modelo

In [ ]:
history = model.fit(x_train, y_train, epochs=50, batch_size=16, validation_split=0.2, verbose=1)

### 📈 4.7. Visualización del entrenamiento

In [ ]:
plt.figure(figsize=(8,4))
plt.plot(history.history['accuracy'], label='Entrenamiento')
plt.plot(history.history['val_accuracy'], label='Validación')
plt.title('Evolución de la accuracy')
plt.legend()
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.show()

### 🧪 4.8. Evaluación final

In [ ]:
loss, acc = model.evaluate(x_test, y_test, verbose=0)
print(f"Exactitud en test: {acc*100:.1f}%")

### 🔍 4.9. Predicciones y Matriz de Confusión

In [ ]:
y_pred = np.argmax(model.predict(x_test), axis=1)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred, target_names=le.classes_, zero_division=0))

In [ ]:
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_)
plt.title("Matriz de confusión")
plt.xlabel("Predicho")
plt.ylabel("Verdadero")
plt.show()

### 🧭 4.10. Exportar el modelo (para Streamlit)

In [ ]:
model.save("./red_neuronal.keras")
pickle.dump((scaler, le), open("./objetos.pkl", "wb"))

## 🎮 Parte 5 - Visualización del Tablero y la Ruta

La idea es:

- Generar un nuevo tablero aleatorio.
- Calcular sus características (features).
- Hacer que la red neuronal prediga el algoritmo más conveniente.
- Ejecutar ese algoritmo y mostrar la ruta sobre el tablero con colores.

### 📚 5.1. Bibliotecas necesarias

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from matplotlib.animation import FuncAnimation
from IPython.display import HTML, Image
import PIL.Image
import urllib.request

### 📦 5.2. Función de predicción

In [ ]:
# Predice el mejor algoritmo usando el modelo entrenado
def predecir_algoritmo(tablero, verbose=1):
    tamanio = tablero.shape[0]
    costo_prom = tablero.mean()
    varianza = tablero.var()
    densidad_cost3 = np.mean(tablero == 3)

    columnas = ["tamanio", "costo_prom", "var_costo", "densidad_cost3"]
    features = pd.DataFrame([[tamanio, costo_prom, varianza, densidad_cost3]], columns=columnas)

    features_scaled = scaler.transform(features)

    predicciones = model.predict(features_scaled, verbose=verbose)

    pred_alg = np.argmax(predicciones, axis=1)[0]
    pred_alg = le.inverse_transform([pred_alg])[0]
    return pred_alg, predicciones

### 🛠️ 5.3. Funciones auxiliares

In [ ]:
# Ejecutar un algoritmo real sobre un tablero
def ejecutar_algoritmo(tablero, algoritmo="A*"):
  costo, nodos, tiempo, camino = None, None, None, None

  # Ejecutar el algoritmo elegido
  if alg_pred == "BFS":
      costo, nodos, tiempo, camino = busqueda_bfs(tablero_test)
  elif alg_pred == "UCS":
      costo, nodos, tiempo, camino = busqueda_generica(tablero_test, algoritmo="UCS")
  elif alg_pred == "Greedy":
      costo, nodos, tiempo, camino = busqueda_generica(tablero_test, algoritmo="Greedy")
  elif alg_pred == "A*":
      costo, nodos, tiempo, camino = busqueda_generica(tablero_test, algoritmo="A*")

  return costo, nodos, tiempo, camino

### 🗺️ 5.4. Visualizaciones del tablero

In [ ]:
# Muestra el tablero, y opcionalmente el camino recorrido
def generar_tablero_estatico(tablero, camino=None, titulo="Tablero"):
    n = tablero.shape[0]
    fig, ax = plt.subplots(figsize=(6,6))
    ax.imshow(tablero, cmap='Blues', origin='upper')

    # mostrar los costos en las celdas
    for i in range(n):
        for j in range(n):
            ax.text(j, i, str(tablero[i,j]), ha='center', va='center', color='black', fontsize=12)

    # dibujar el camino
    if camino:
        xs, ys = zip(*camino)
        ax.plot(ys, xs, color='red', linewidth=2)

    # marcar con círculos el inicio y la meta
    ax.scatter(0, 0, c='gold', s=120, label='Inicio')
    ax.scatter(n-1, n-1, c='green', s=120, label='Meta')

    # graficar
    ax.set_title(titulo)
    ax.legend(fontsize=8)
    plt.show()

In [ ]:
def generar_tablero_animado(tablero, camino, titulo="Tablero", nombre_archivo="animacion.gif"):
    n = tablero.shape[0]
    fig, ax = plt.subplots(figsize=(6,6))
    ax.imshow(tablero, cmap='Blues', origin='upper')

    # mostrar los costos en las celdas
    for i in range(n):
        for j in range(n):
            ax.text(j, i, str(tablero[i,j]), ha='center', va='center', color='black', fontsize=12)

    # dibujar camino y meta
    xs, ys = zip(*camino)
    ax.plot(ys, xs, color='red', linewidth=2, alpha=0.4)
    ax.scatter(0, 0, c='gold', s=120, label='Inicio')
    ax.scatter(n-1, n-1, c='green', s=120, label='Meta')

    # cargar la imagen del auto
    img_url = "https://github.com/andres-garcia-alves/issd-dsia/raw/refs/heads/main/Proyecto-Final/miscelaneos/auto.png"
    with urllib.request.urlopen(img_url) as url:
        img_data = np.array(PIL.Image.open(url))
    imagebox = OffsetImage(img_data, zoom=0.70)
    ab = AnnotationBbox(imagebox, camino[0][::-1], frameon=False)
    ax.add_artist(ab)

    ax.set_title(titulo)
    ax.legend(fontsize=8)

    # generar interpolaciones (para un movimiento fluido)
    posiciones_interp = []
    pasos_intermedios = 10
    for (x1, y1), (x2, y2) in zip(camino[:-1], camino[1:]):
        for t in np.linspace(0, 1, pasos_intermedios, endpoint=False):
            xi = x1 + (x2 - x1) * t
            yi = y1 + (y2 - y1) * t
            posiciones_interp.append((xi, yi))
    posiciones_interp.append(camino[-1])  # último punto exacto

    # callback invocado por matplotlib por cada frame
    def update(frame):
        # borrar el auto anterior
        for artist in ax.artists: artist.remove()

        # dibujar el auto en la nueva posición
        x, y = posiciones_interp[frame]
        ab_new = AnnotationBbox(imagebox, (y, x), frameon=False)
        ax.add_artist(ab_new)

        return ab_new,

    # crear y guardar el gif de la animación
    fps = 25
    anim = FuncAnimation(fig, update, frames=len(posiciones_interp), interval = 1000/fps, blit=True, repeat=False)
    anim.save(nombre_archivo, writer='pillow', fps=fps)

    plt.close(fig)

### 🧩 5.5. Ejemplo completo

In [ ]:
# Generar un tablero aleatorio
tablero_test = generar_tablero(n=random.choice([5,6,7]))
print("Tablero generado:")
print(tablero_test, '\n')

In [ ]:
# Predicción del modelo
alg_pred, preds = predecir_algoritmo(tablero_test)
print("Clasificación:", preds, '\n')
print("Predicción de mejor algoritmo:", alg_pred)

In [ ]:
# Ejecutar el algoritmo de búsqueda
costo, nodos, tiempo, camino = ejecutar_algoritmo(tablero_test, algoritmo=alg_pred)
print(camino)

In [ ]:
# Mostrar el tablero y la ruta de forma gráfica
print(f"\nCosto total: {costo}, Nodos expandidos: {nodos}")
generar_tablero_estatico(tablero_test, camino, titulo=f"Algoritmo sugerido: {alg_pred}")

In [ ]:
# Generar una animación para el tablero y la ruta
generar_tablero_animado(tablero=tablero_test, camino=camino, titulo=f"Algoritmo sugerido: {alg_pred}", nombre_archivo="tablero-animado.gif")

In [ ]:
# Mostrar la animación para el tablero y la ruta
print(f"\nCosto total: {costo}, Nodos expandidos: {nodos}")
Image(filename="tablero-animado.gif")  # mostrar el tablero animado

Detalle del gráfico: 🖼️

* El tablero con los valores de costo en cada celda.
* Inicio (verde) y meta (amarillo).
* Camino sugerido (en rojo).
* Nombre del algoritmo elegido por la red neuronal.

## 📝 Parte 6 - Evaluación del desempeño del modelo

### 🧠 6.1. Evaluar si el modelo elige correctamente

La idea es:

- Generar varios tableros nuevos (datos que el modelo no vio durante el entrenamiento).
- Calcular cuál algoritmo realmente tiene mejor desempeño (menor costo).
- Ver si la red neuronal eligió el correcto.
- Calcular la precisión global (accuracy).

### ✅ 6.2. Evaluar Exactitud

In [ ]:
def evaluar_modelo(model, n_pruebas=100):
    aciertos = 0
    total = 0

    for _ in range(n_pruebas):
        tablero = generar_tablero(n=random.choice([5,6,7,8]))

        mejor_alg, detalles = probar_algoritmos(tablero)          # resultados reales
        pred_alg, preds = predecir_algoritmo(tablero, verbose=0)  # predicción del modelo

        if pred_alg == mejor_alg: aciertos += 1
        total += 1

    acc = aciertos / total
    return acc

In [ ]:
acc = evaluar_modelo(model, n_pruebas=100)
print(f"✅ Exactitud al elegir el mejor algoritmo: {acc*100:.1f}%")

💬 Interpretación:

* El modelo logra una precisión alrrededor del 90% al seleccionar el algoritmo que efectivamente produce el menor costo de búsqueda.

* Esto implica que aprendió una relación entre las características del entorno (tamaño, variabilidad, obstáculos) y el desempeño de cada algoritmo.

* En un sistema de GPS, donde el entorno cambia constantemente, este tipo de red podría servir como selector dinámico entre distintos métodos de planificación.

### 🧩 6.3. Estadísticas por separado

In [ ]:
from collections import Counter

def evaluar_detallado(model, n_pruebas=100):
    resultados = []

    for _ in range(n_pruebas):
        tablero = generar_tablero(n=random.choice([5,6,7,8]))

        mejor_alg, detalles = probar_algoritmos(tablero)          # resultados reales
        pred_alg, preds = predecir_algoritmo(tablero, verbose=0)  # predicción del modelo

        resultados.append((mejor_alg, pred_alg))

    reales, preds = zip(*resultados)
    acc = np.mean(np.array(reales) == np.array(preds))

    conteo = Counter(resultados)
    return conteo

In [ ]:
conteo = evaluar_detallado(model, n_pruebas=100)
conteo

In [ ]:
print(f"✅ Exactitud: {acc*100:.2f}% \n\n")

print("📈 Matriz de confusión (real vs predicho):")
conf_matrix = pd.DataFrame({
    "Predijo A*":     [conteo[('A*', 'A*')],     conteo[('A*', 'UCS')],     conteo[('A*', 'Greedy')],     conteo[('A*', 'BFS')]],
    "Predijo USC":    [conteo[("UCS", "A*")],    conteo[("UCS", "UCS")],    conteo[("UCS", "Greedy")],    conteo[('UCS', 'BFS')]],
    "Predijo Greedy": [conteo[("Greedy", "A*")], conteo[("Greedy", "UCS")], conteo[("Greedy", "Greedy")], conteo[('Greedy', 'BFS')]],
    "Predijo BFS":    [conteo[("BFS", "A*")],    conteo[("BFS", "UCS")],    conteo[("BFS", "Greedy")],    conteo[("BFS", "BFS")]]
}, index=["Real A*", "Real UCS", "Real Greedy", "BFS"])
print(conf_matrix, "\n\n")

print("📈 Reporte de clasificación:")
print(classification_report(y_test, y_pred, target_names=le.classes_, zero_division=0))

## ✒️ Parte 7 - Conclusiones:


### 💬 7.1. Análisis conceptual

> El entrenamiento del modelo de red neuronal se puede entender como un proceso de búsqueda en el espacio de soluciones (pesos), donde el algoritmo de optimización (Adam) actúa como un agente que minimiza la función de pérdida (loss).  
> Este proceso es análogo a los algoritmos de búsqueda informada (como A*) que exploran un espacio de soluciones guiados por una heurística (la función de pérdida, en este caso).  
> Así, el modelo aprende a seleccionar el algoritmo de búsqueda más eficiente según las características del tablero, optimizando su desempeño en base a los datos con la experiencia previa (el dataset sintético con las simulaciones).

### 💎 7.2. Algunas posibles mejoras

- Dataset sintético:
  - Aumentar el tamaño de los tableros, por ej. 50x50 o más.
  - Tableros rectangulares.
  - Posiciones de inicio y meta aleatorias.

- Algoritmos:
  - Incorporar más algoritmos, por ej. Deep-First Search (DFS).

- Red Neuronal:
  - Explorar más arquitecturas (nro de capas, funciones de activación, etc) que mejoren la precisión del clasificador.

- Deploy (Streamlit):
  - Permitir al usuario que 'dibuje' (construya) su propio tablero.

### 📌 7.3. Observaciones

> Se combinaron técnicas clásicas de búsqueda (BFS, A*, UCS, Greedy) con un modelo de red neuronal entrenado sobre tableros sintéticos.  
La IA aprendió a predecir cuál algoritmo tendrá mejor desempeño según las características del entorno, funcionando como un meta-agente adaptativo.

> El sistema no solo sugiere el algoritmo más eficiente según las condiciones del entorno, sino que también muestra visualmente la solución encontrada, permitiendo observar cómo varía la trayectoria óptima según el tipo de heurística y los costos del entorno.

> Adicionalmente, de la sección de Evaluación del Desempeño, demuestro que:
> - Los algoritmos clásicos funcionaron correctamente.
> - La red neuronal aprendió a decidir inteligentemente cuál usar según las condiciones del entorno.
> - Se integran las dos ramas de la materia: algoritmos de búsqueda y aprendizaje automático (TensorFlow/Keras).
